### ISSUE TITLE
Error When Key Generated

### ISSUE THREAD

**Issue by cyrixdx4** [ReverseAllTheThings/PowervaultKeygen#1]
Trying to generate a key for an old MD3200 and I got this error after compiling with VS2019:

ee the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.FormatException: Could not find any recognizable digits.
   at System.ParseNumbers.StringToInt(String s, Int32 radix, Int32 flags, Int32* currPos)
   at System.Convert.ToByte(String value, Int32 fromBase)
   at DellPowerVaultFeatureKeygen.Utility.HexStringToByteArray(String hex) in C:\Users\PowervaultKeygen-master\PowervaultKeygen-master\DellPowerVaultFeatureKeygen\Utility.cs:line 25
   at DellPowerVaultFeatureKeygen.MainForm.Generate(Object sender, EventArgs e) in C:\Users\PowervaultKeygen-master\PowervaultKeygen-master\DellPowerVaultFeatureKeygen\Forms\MainForm.cs:line 26
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4150.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

**Comment by lemassykoi** [comment]
Hi, no error here with VS 2017 Community.
Just had to install Dot Net Framework 4.7.2 Dev Pack, and build was OK, in 2 seconds.

Key generated, it's amazingly simple. Thank you very much, @ReverseAllTheThings

**Comment by cyrixdx4** [comment]
I tried VS 2017 community and still got the same error when i tried to enable the feature using the identifiers of snapshot, ssd, virtualdiskcopy etc,  as describe in the capability file.

"Could not find any recongnizable digits"

  Is there a list of parameters or names and values that work for the FEature Enable Identifier? I must be missing something here as the code compiles but when executed it crashes out.

**Comment by cyrixdx4** [comment]
The fix apparently is to use the NUMBER of the init and not the text value which then generates the proper key output. I wish this was made more clear somewhere.  I'll have to test and confirm the key is working when my array is reassembled.

**Comment by lemassykoi** [comment]
I didn't select anything, just put the number the soft was waiting for, and generate. That's all. And the generated key was containig all premium features (didn't know we can choose)

**Comment by cyrixdx4** [comment]
What was the number you used? I don't see any list of how to add all the features at once without generating multiple keys.

**Comment by lemassykoi** [comment]
I don't need to use any "number". After build, there was 3 files, located in /bin/Debug : 
![image](https://user-images.githubusercontent.com/16377344/86050000-710dc080-ba53-11ea-818b-bec3d309edb4.png)

then I started the .exe : 
![image](https://user-images.githubusercontent.com/16377344/86050092-900c5280-ba53-11ea-9823-bfdf1e75709e.png)

I put my number from Dell Powervault Modular Disk Storage Manager : 
![image](https://user-images.githubusercontent.com/16377344/86050307-f6917080-ba53-11ea-85ea-1dbf01f97fe4.png)

and keygen gives me a .key file, and when I download it to MD3220i with button next to my number, it was recognized as licence for all.
![image](https://user-images.githubusercontent.com/16377344/86050443-293b6900-ba54-11ea-8d2b-ff5836eb820b.png)
